<?php
/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$debugEnabled = Mage::helper('turpentine/esi')->getEsiDebugEnabled();
$isAjax = Mage::app()->getRequest()->getParam('is_ajax', false);

if (!$isAjax) {
	if ($debugEnabled) {
		echo sprintf('<!-- ESI START [%s] -->', $this->getNameInLayout()),"\n";
		echo sprintf('<!-- ESI URL: %s -->', $this->getEsiUrl()),"\n";
	}
	else {
		echo '<!-- ESI START DUMMY COMMENT [] -->',"\n";
		echo '<!-- ESI URL DUMMY COMMENT -->',"\n";
	}
	// https://github.com/PHOENIX-MEDIA/Magento-PageCache-powered-by-Varnish/issues/17#issuecomment-93674983
	echo sprintf('<esi:remove>ESI processing not enabled</esi:remove>%s<!--esi <esi:include src=\'%s\' /> -->', "\n", $this->getEsiUrl()),"\n";
	if ($debugEnabled) {
		echo sprintf('<!-- ESI END [%s] -->', $this->getNameInLayout()),"\n";
	}
	else {
		echo '<!-- ESI END DUMMY COMMENT [] -->',"\n";
	}
}