<?php
/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */

$debugEnabled = (bool)Mage::helper( 'turpentine/esi' )->getEsiDebugEnabled();
$isAjax = Mage::app()->getRequest()->getParam('is_ajax', false);

if( !$isAjax ) {
    if( $debugEnabled ) {
        echo sprintf( '<!-- ESI START [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
        echo sprintf( '<!-- ESI URL: %s -->', $this->getEsiUrl() ) . PHP_EOL;
    } else {
        echo '<!-- ESI START DUMMY COMMENT [] -->' . PHP_EOL;
        echo '<!-- ESI URL DUMMY COMMENT -->' . PHP_EOL;
    }
    echo sprintf( '<esi:remove>ESI processing not enabled</esi:remove>
<!--esi <esi:include src="%s" /> -->',
        $this->getEsiUrl() ) . PHP_EOL;
    if( $debugEnabled ) {
        echo sprintf( '<!-- ESI END [%s] -->', $this->getNameInLayout() ) . PHP_EOL;
    } else {
        echo '<!-- ESI END DUMMY COMMENT [] -->' . PHP_EOL;
    }
}