<?php
/**
 * Nexcess.net Turpentine Extension for Magento
 * Copyright (C) 2012  Nexcess.net L.L.C.
 *
 * This program is free software, you can redistribute it or modify
 * it under the terms of the GNU General Public License (GPL) as published
 * by the free software foundation, either version 2 of the license, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but without any warranty, without even the implied warranty of
 * merchantability or fitness for a particular purpose. See the
 * GNU General Public License (GPL) for more details.
 */
?>

<?php if ($this->helper('turpentine/varnish')->shouldDisplayNotice()): ?>
	<div class="varnish-global-notice">
		<div class="notice-inner">
			<p>
				<strong><?php echo $this->__('The cookie that allows bypassing Varnish is present in your browser.') ?></strong>
				<br /><?php echo $this->__('Remember that this navigation mode should be only activated for testing. You will suffer a decline in overall performance until you delete this cookie.') ?>
			</p>
		</div>
	</div>
<?php endif ?>